export interface ToolDefinition {
  id: string;
  name: string;
  description: string;
  category: 'images' | 'documents' | 'developer' | 'text' | 'utilities';
  route: string;
  status: 'active' | 'partial' | 'planned' | 'deprecated' | 'alias' | 'internal';
  indexable: boolean;
  capabilities: string[];
  searchIntents: string[];
  relatedTools: string[];
  featured: boolean;
}

export const TOOL_REGISTRY: ToolDefinition[] = [
  {
    id: 'client-side-private-image-compressor',
    name: 'Image Compressor',
    description: 'Compress PNG, JPEG, WebP, and AVIF images locally with quality controls.',
    category: 'images',
    route: '/client-side-private-image-compressor',
    status: 'active',
    indexable: true,
    capabilities: ['compression', 'wasm', 'batch'],
    searchIntents: ['compress image offline', 'private image compressor', 'wasm jpeg compressor'],
    relatedTools: ['bulk-image-compressor-offline', 'compress-png-images-online', 'compress-image-to-exact-size-kb', 'convert-heic-to-jpg-locally'],
    featured: true
  },
  {
    id: 'convert-heic-to-jpg-locally',
    name: 'HEIC to JPG',
    description: 'Convert Apple iPhone HEIC/HEIF photos to universal JPEG format.',
    category: 'images',
    route: '/convert-heic-to-jpg-locally',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'heic', 'batch'],
    searchIntents: ['convert heic to jpg', 'heic viewer offline', 'apple heic converter'],
    relatedTools: ['client-side-private-image-compressor', 'bulk-image-compressor-offline', 'compress-image-to-exact-size-kb', 'convert-image-to-pdf'],
    featured: true
  },
  {
    id: 'strip-exif-metadata-online-private',
    name: 'EXIF Metadata Stripper',
    description: 'Remove GPS coordinates, camera specs, and timestamps from images.',
    category: 'images',
    route: '/strip-exif-metadata-online-private',
    status: 'active',
    indexable: true,
    capabilities: ['privacy', 'metadata', 'exif'],
    searchIntents: ['remove exif metadata', 'strip image location online', 'privacy metadata cleaner'],
    relatedTools: ['blur-sensitive-image-privacy-pixelator', 'client-side-private-image-compressor', 'dpi-ppi-converter-change-image-resolution', 'convert-heic-to-jpg-locally'],
    featured: true
  },
  {
    id: 'bulk-image-compressor-offline',
    name: 'Bulk Image Compressor',
    description: 'Batch optimize and convert multiple images simultaneously.',
    category: 'images',
    route: '/bulk-image-compressor-offline',
    status: 'active',
    indexable: true,
    capabilities: ['batch', 'compression', 'zip'],
    searchIntents: ['bulk image compressor', 'batch resize images offline', 'multiple image optimizer'],
    relatedTools: ['client-side-private-image-compressor', 'compress-image-to-exact-size-kb', 'compress-png-images-online', 'convert-image-to-pdf'],
    featured: true
  },
  {
    id: 'compress-png-images-online',
    name: 'Lossless PNG Compressor',
    description: 'Optimize PNG files using WebAssembly quantizers with zero quality loss.',
    category: 'images',
    route: '/compress-png-images-online',
    status: 'active',
    indexable: true,
    capabilities: ['compression', 'png', 'wasm'],
    searchIntents: ['compress png lossless', 'png quantizer online', 'shrink png size'],
    relatedTools: ['convert-png-to-webp-lossless', 'convert-webp-to-png-transparent', 'client-side-private-image-compressor', 'convert-png-to-jpg-white-background'],
    featured: false
  },
  {
    id: 'convert-webp-to-png-transparent',
    name: 'WebP to PNG',
    description: 'Convert WebP images to standard PNG with alpha transparency preserved.',
    category: 'images',
    route: '/convert-webp-to-png-transparent',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'webp', 'png'],
    searchIntents: ['convert webp to png', 'transparent webp converter'],
    relatedTools: ['convert-png-to-webp-lossless', 'compress-png-images-online', 'convert-jpg-to-webp-browser', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-avif-to-jpg-converter',
    name: 'AVIF to JPG',
    description: 'Decode AVIF image files and convert them to standard JPEG format.',
    category: 'images',
    route: '/convert-avif-to-jpg-converter',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'avif', 'jpg'],
    searchIntents: ['convert avif to jpg', 'avif decoder online'],
    relatedTools: ['convert-to-avif-online-free', 'convert-heic-to-jpg-locally', 'client-side-private-image-compressor', 'convert-jpg-to-webp-browser'],
    featured: false
  },
  {
    id: 'convert-svg-to-png-transparent',
    name: 'SVG to PNG',
    description: 'Rasterize vector SVG files into crisp, high-resolution PNG images.',
    category: 'images',
    route: '/convert-svg-to-png-transparent',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'svg', 'rasterize'],
    searchIntents: ['convert svg to png', 'vector to raster online'],
    relatedTools: ['convert-png-to-webp-lossless', 'client-side-image-to-base64', 'compress-png-images-online'],
    featured: false
  },
  {
    id: 'convert-png-to-webp-lossless',
    name: 'PNG to WebP',
    description: 'Convert PNG graphics into high-efficiency WebP files.',
    category: 'images',
    route: '/convert-png-to-webp-lossless',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'png', 'webp'],
    searchIntents: ['convert png to webp', 'lossless webp encoder'],
    relatedTools: ['convert-webp-to-png-transparent', 'compress-png-images-online', 'convert-jpg-to-webp-browser', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'crop-image-to-exact-aspect-ratio',
    name: 'Image Cropper',
    description: 'Crop images to 1:1, 16:9, 4:3, passport, or custom aspect ratios.',
    category: 'images',
    route: '/crop-image-to-exact-aspect-ratio',
    status: 'active',
    indexable: true,
    capabilities: ['crop', 'editing', 'resize'],
    searchIntents: ['crop image aspect ratio', 'square photo cropper online'],
    relatedTools: ['dpi-ppi-converter-change-image-resolution', 'add-text-watermark-image-browser', 'blur-sensitive-image-privacy-pixelator', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'add-text-watermark-image-browser',
    name: 'Image Watermark',
    description: 'Overlay custom text watermarks onto images directly in your browser.',
    category: 'images',
    route: '/add-text-watermark-image-browser',
    status: 'active',
    indexable: true,
    capabilities: ['watermark', 'editing', 'security'],
    searchIntents: ['add text watermark to image', 'watermark photos offline'],
    relatedTools: ['blur-sensitive-image-privacy-pixelator', 'crop-image-to-exact-aspect-ratio', 'strip-exif-metadata-online-private', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-tiff-bmp-to-jpg',
    name: 'TIFF & BMP to JPG',
    description: 'Convert legacy TIFF and BMP raster images to standard JPEG.',
    category: 'images',
    route: '/convert-tiff-bmp-to-jpg',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'tiff', 'bmp'],
    searchIntents: ['convert tiff to jpg', 'bmp converter online'],
    relatedTools: ['convert-heic-to-jpg-locally', 'convert-png-to-jpg-white-background', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'dpi-ppi-converter-change-image-resolution',
    name: 'DPI & PPI Resizer',
    description: 'Adjust image print resolution metadata for documents and printing.',
    category: 'images',
    route: '/dpi-ppi-converter-change-image-resolution',
    status: 'active',
    indexable: true,
    capabilities: ['resolution', 'dpi', 'print'],
    searchIntents: ['change image dpi online', 'ppi resizer tool'],
    relatedTools: ['crop-image-to-exact-aspect-ratio', 'convert-image-to-pdf', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-jpg-to-webp-browser',
    name: 'JPG to WebP',
    description: 'Convert JPEG photos to high-compression WebP format.',
    category: 'images',
    route: '/convert-jpg-to-webp-browser',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'jpg', 'webp'],
    searchIntents: ['convert jpg to webp', 'jpeg to webp converter'],
    relatedTools: ['convert-png-to-webp-lossless', 'convert-webp-to-png-transparent', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'compress-image-to-exact-size-kb',
    name: 'Exact Size Compressor (KB)',
    description: 'Shrink photos to precise target file sizes (e.g. 50KB, 100KB, 200KB).',
    category: 'images',
    route: '/compress-image-to-exact-size-kb',
    status: 'active',
    indexable: true,
    capabilities: ['compression', 'target-size', 'kb'],
    searchIntents: ['compress image to kb', 'shrink photo to 100kb', 'image size reducer kb'],
    relatedTools: ['client-side-private-image-compressor', 'bulk-image-compressor-offline', 'compress-png-images-online'],
    featured: true
  },
  {
    id: 'convert-ico-to-png-favicon-extractor',
    name: 'ICO Favicon to PNG',
    description: 'Extract multi-resolution ICO icon files into transparent PNGs.',
    category: 'images',
    route: '/convert-ico-to-png-favicon-extractor',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'ico', 'favicon'],
    searchIntents: ['convert ico to png', 'extract favicon online'],
    relatedTools: ['convert-png-to-webp-lossless', 'client-side-image-to-base64', 'convert-svg-to-png-transparent'],
    featured: false
  },
  {
    id: 'convert-png-to-jpg-white-background',
    name: 'PNG to JPG (White Fill)',
    description: 'Flatten transparent PNG graphics onto a clean white background.',
    category: 'images',
    route: '/convert-png-to-jpg-white-background',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'png', 'jpg', 'flatten'],
    searchIntents: ['convert png to jpg white background', 'remove transparency jpeg'],
    relatedTools: ['convert-webp-to-png-transparent', 'compress-png-images-online', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'blur-sensitive-image-privacy-pixelator',
    name: 'Image Blur & Pixelate',
    description: 'Obscure faces, personal data, and sensitive areas on photos.',
    category: 'images',
    route: '/blur-sensitive-image-privacy-pixelator',
    status: 'active',
    indexable: true,
    capabilities: ['privacy', 'blur', 'pixelate'],
    searchIntents: ['blur sensitive image data', 'pixelate face online private'],
    relatedTools: ['strip-exif-metadata-online-private', 'add-text-watermark-image-browser', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-to-avif-online-free',
    name: 'Convert to AVIF',
    description: 'Encode images into next-generation AVIF format with superior compression.',
    category: 'images',
    route: '/convert-to-avif-online-free',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'avif', 'compression'],
    searchIntents: ['convert to avif online', 'image to avif encoder'],
    relatedTools: ['convert-avif-to-jpg-converter', 'convert-png-to-webp-lossless', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-image-to-pdf',
    name: 'Images to PDF',
    description: 'Combine multiple JPG, PNG, or HEIC photos into a multi-page PDF.',
    category: 'documents',
    route: '/convert-image-to-pdf',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'conversion', 'images', 'merge'],
    searchIntents: ['jpg to pdf', 'image to pdf converter', 'combine images to pdf', 'png to pdf offline'],
    relatedTools: ['merge-pdf', 'convert-pdf-pages-to-jpg-images', 'secure-document-compressor-pdf', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF documents into a single organized file.',
    category: 'documents',
    route: '/merge-pdf',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'merge', 'offline'],
    searchIntents: ['merge pdf files online', 'combine pdfs offline', 'join pdf documents free'],
    relatedTools: ['split-pdf', 'convert-pdf-pages-to-jpg-images', 'secure-document-compressor-pdf', 'compress-image-to-exact-size-kb', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract specific pages or page ranges into separate PDF documents.',
    category: 'documents',
    route: '/split-pdf',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'split', 'extraction'],
    searchIntents: ['split pdf pages online', 'extract pdf pages offline', 'pdf page separator'],
    relatedTools: ['merge-pdf', 'convert-pdf-pages-to-jpg-images', 'secure-document-compressor-pdf', 'compress-image-to-exact-size-kb', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'convert-pdf-pages-to-jpg-images',
    name: 'PDF to JPG',
    description: 'Render PDF document pages into high-resolution JPG images.',
    category: 'documents',
    route: '/convert-pdf-pages-to-jpg-images',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'conversion', 'extraction'],
    searchIntents: ['convert pdf pages to jpg', 'extract images from pdf offline'],
    relatedTools: ['merge-pdf', 'split-pdf', 'compress-image-to-exact-size-kb', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'secure-document-compressor-pdf',
    name: 'Compress PDF',
    description: 'Shrink and optimize PDF file sizes directly in browser memory.',
    category: 'documents',
    route: '/secure-document-compressor-pdf',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'compression', 'security'],
    searchIntents: ['compress pdf offline', 'secure document compressor'],
    relatedTools: ['merge-pdf', 'split-pdf', 'convert-pdf-pages-to-jpg-images', 'compress-image-to-exact-size-kb', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'client-side-image-to-base64',
    name: 'Image to Base64',
    description: 'Encode image files into Data URI Base64 strings for CSS and HTML.',
    category: 'developer',
    route: '/client-side-image-to-base64',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'base64', 'encoding'],
    searchIntents: ['image to base64 converter', 'encode image data uri'],
    relatedTools: ['base64-to-image-converter', 'json-formatter-validator', 'palette-color-extractor-image-hex'],
    featured: true
  },
  {
    id: 'base64-to-image-converter',
    name: 'Base64 to Image',
    description: 'Decode Base64 strings back into downloadable image files instantly.',
    category: 'developer',
    route: '/base64-to-image-converter',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'base64', 'decoding'],
    searchIntents: ['base64 to image decoder', 'convert base64 to png', 'decode base64 string offline'],
    relatedTools: ['client-side-image-to-base64', 'json-formatter-validator', 'jwt-decoder'],
    featured: true
  },
  {
    id: 'palette-color-extractor-image-hex',
    name: 'Color Palette Extractor',
    description: 'Extract dominant HEX and RGB color palettes from any photo.',
    category: 'utilities',
    route: '/palette-color-extractor-image-hex',
    status: 'active',
    indexable: true,
    capabilities: ['design', 'colors', 'palette'],
    searchIntents: ['extract color palette from image', 'image color hex picker'],
    relatedTools: ['json-formatter-validator', 'client-side-image-to-base64', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'json-formatter-validator',
    name: 'JSON Formatter & Validator',
    description: 'Format, prettify, repair, and inspect JSON with syntax diagnostics.',
    category: 'developer',
    route: '/json-formatter-validator',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'json', 'formatter', 'validator', 'tree-view', 'minify'],
    searchIntents: ['json formatter', 'json validator online', 'beautify json offline', 'format json private', 'json tree viewer'],
    relatedTools: ['regex-tester', 'jwt-decoder', 'csv-to-json-converter', 'client-side-image-to-base64'],
    featured: true
  },
  {
    id: 'csv-to-json-converter',
    name: 'CSV ↔ JSON Converter',
    description: 'Convert tabular CSV/TSV data to JSON arrays and vice versa.',
    category: 'developer',
    route: '/csv-to-json-converter',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'csv', 'json', 'converter', 'tsv', 'table-view'],
    searchIntents: ['csv to json', 'json to csv', 'convert csv to json offline', 'csv json converter private', 'tsv to json'],
    relatedTools: ['regex-tester', 'json-formatter-validator', 'jwt-decoder', 'client-side-image-to-base64'],
    featured: true
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Token headers, claims, and signatures.',
    category: 'developer',
    route: '/jwt-decoder',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'jwt', 'decoder', 'debugger', 'security', 'auth'],
    searchIntents: ['jwt decoder', 'decode jwt online', 'jwt debugger offline', 'jwt token viewer', 'jwt inspector', 'verify jwt signature client-side'],
    relatedTools: ['regex-tester', 'json-formatter-validator', 'csv-to-json-converter', 'client-side-image-to-base64'],
    featured: true
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test JavaScript regular expressions with real-time match highlighting.',
    category: 'developer',
    route: '/regex-tester',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'regex', 'tester', 'debugger', 'string-diagnostics', 'replace', 'unicode'],
    searchIntents: ['regex tester', 'regular expression tester', 'regex debugger', 'regex match tester', 'test regex online', 'javascript regex tester'],
    relatedTools: ['markdown-live-preview', 'json-formatter-validator', 'jwt-decoder', 'csv-to-json-converter'],
    featured: true
  },
  {
    id: 'markdown-live-preview',
    name: 'Markdown Live Preview',
    description: 'Write GFM Markdown with live rendering and instant HTML export.',
    category: 'text',
    route: '/markdown-live-preview',
    status: 'active',
    indexable: true,
    capabilities: ['text', 'markdown', 'gfm', 'previewer', 'converter', 'html-export', 'sanitizer', 'unicode'],
    searchIntents: ['markdown live preview', 'gfm editor online', 'markdown to html converter', 'markdown editor private', 'markdown preview offline'],
    relatedTools: ['text-diff', 'regex-tester', 'json-formatter-validator', 'jwt-decoder'],
    featured: true
  },
  {
    id: 'text-diff',
    name: 'Text Diff & Comparator',
    description: 'Compare text snippets side-by-side with character-level diff highlighting.',
    category: 'text',
    route: '/text-diff',
    status: 'active',
    indexable: true,
    capabilities: ['text', 'diff', 'comparison', 'side-by-side', 'unified', 'patch', 'unicode'],
    searchIntents: ['text diff', 'diff viewer online', 'compare text side by side', 'code diff checker', 'diff comparator offline', 'unified diff viewer'],
    relatedTools: ['markdown-live-preview', 'regex-tester', 'json-formatter-validator', 'csv-to-json-converter'],
    featured: true
  },
  {
    id: 'word-character-counter-online',
    name: 'Word & Character Counter',
    description: 'Instantly count words, characters, sentences, and paragraphs as you type.',
    category: 'text',
    route: '/word-character-counter-online',
    status: 'active',
    indexable: true,
    capabilities: ['text', 'count', 'words', 'characters'],
    searchIntents: ['word counter online', 'character count tool', 'how many words is this'],
    relatedTools: ['text-diff', 'markdown-live-preview', 'regex-tester'],
    featured: true
  },
  {
    id: 'secure-password-generator-online',
    name: 'Secure Password Generator',
    description: 'Generate strong, cryptographically secure random passwords offline.',
    category: 'developer',
    route: '/secure-password-generator-online',
    status: 'active',
    indexable: true,
    capabilities: ['security', 'passwords', 'random', 'generator'],
    searchIntents: ['secure password generator', 'random password maker', 'strong password creator offline'],
    relatedTools: ['jwt-decoder', 'base64-to-image-converter', 'word-character-counter-online'],
    featured: true
  }
];
